students = ['Naveen', 'Saurabh', 'Ayush' , 'Ranjesh']
print(students)
print(students[3])
print(students[0:2])
print(type(students))
print(len(students))
print(students)
print(dir(list))
print(students.append('Vineet'))
print(students)
print(students.insert(3,'Kartik'))
print(students)
print(students.index('Ayush'))
print(students.count('Saurabh'))
print(students.remove('Kartik'))
print(students)
print(students.pop())
print(students.reverse())
print(students)
print(students.sort())
print(students)
list = ['123','192.168.10.100', 'jai']
"""students.extend(list)
studentsCopy = students.copy()
print(students)
print(studentsCopy) """
students[3] =  'Kartik'
print(students)
#print(studentsCopy)
#print(studentsCopy)
#students.append(list)
#print(students)
students.append(list)
studentsCopy = students.copy()
list[0] = '456'
print(students)
print(studentsCopy)